---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  client_rb:
    chef_license: accept

verifier:
  name: inspec

platforms:
  - name: centos-7
  - name: ubuntu-18.04

suites:
  - name: default
    run_list:
      - recipe[apache::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:

